# 实现 
# mHC: Manifold-Constrained Hyper-Connections
# https://arxiv.org/abs/2409.19606
# https://arxiv.org/pdf/2512.24880

import torch
import torch.nn as nn
import torch.nn.functional as F
import math
import warnings
from math import sqrt
import pdb
from mamba_ssm import Mamba
import matplotlib.pyplot as plt
import numpy as np
def _no_grad_trunc_normal_(tensor, mean, std, a, b):
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1. + math.erf(x / math.sqrt(2.))) / 2.

    if (mean < a - 2 * std) or (mean > b + 2 * std):
        warnings.warn("mean is more than 2 std from [a, b] in nn.init.trunc_normal_. "
                      "The distribution of values may be incorrect.",
                      stacklevel=2)

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values
        l = norm_cdf((a - mean) / std)
        u = norm_cdf((b - mean) / std)

        # Uniformly fill tensor with values from [l, u], then translate to
        # [2l-1, 2u-1].
        tensor.uniform_(2 * l - 1, 2 * u - 1)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.))
        tensor.add_(mean)

        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)
        return tensor

def trunc_normal_(tensor, mean: float = 0., std: float = 1., a: float = -2., b: float = 2.):
    r"""Fills the input Tensor with values drawn from a truncated
    normal distribution. The values are effectively drawn from the
    normal distribution :math:`\mathcal{N}(\text{mean}, \text{std}^2)`
    with values outside :math:`[a, b]` redrawn until they are within
    the bounds. The method used for generating the random values works
    best when :math:`a \leq \text{mean} \leq b`.

    Args:
        tensor: an n-dimensional `torch.Tensor`
        mean: the mean of the normal distribution
        std: the standard deviation of the normal distribution
        a: the minimum cutoff value
        b: the maximum cutoff value

    Examples:
        >>> w = torch.empty(3, 5)
        >>> nn.init.trunc_normal_(w)
    """
    return _no_grad_trunc_normal_(tensor, mean, std, a, b)

class SinusoidalPositionEncoding(nn.Module):
    """正弦位置编码，将原始 x,y 坐标编码为高维特征"""
    def __init__(self, d_model, max_len=512):
        super().__init__()
        assert d_model % 2 == 0
        self.d_model = d_model
        # 预计算频率分量
        div_term = torch.exp(torch.arange(0, d_model, 2).float() * (-math.log(10000.0) / d_model))
        self.register_buffer('div_term', div_term)
        self.max_len = max_len
    
    def forward(self, pos):
        """
        pos: (batch, seq_len) 或 (batch, seq_len, 1) - 原始坐标值
        returns: (batch, seq_len, d_model)
        """
        if pos.dim() == 3:
            pos = pos.squeeze(-1)
        # 归一化到 [0, 1] 范围
        pos_normalized = pos / self.max_len
        # 扩展维度: (batch, seq_len, d_model//2)
        pos_expanded = pos_normalized.unsqueeze(-1) * self.div_term * self.max_len
        # 交替 sin/cos
        pe = torch.zeros(*pos.shape, self.d_model, device=pos.device, dtype=pos.dtype)
        pe[..., 0::2] = torch.sin(pos_expanded)
        pe[..., 1::2] = torch.cos(pos_expanded)
        return pe

def drop_path(x, drop_prob: float = 0., training: bool = False, scale_by_keep: bool = True):
    """Drop paths (Stochastic Depth) per sample (when applied in main path of residual blocks).

    This is the same as the DropConnect impl I created for EfficientNet, etc networks, however,
    the original name is misleading as 'Drop Connect' is a different form of dropout in a separate paper...
    See discussion: https://github.com/tensorflow/tpu/issues/494#issuecomment-532968956 ... I've opted for
    changing the layer and argument names to 'drop path' rather than mix DropConnect as a layer name and use
    'survival rate' as the argument.

    """
    if drop_prob == 0. or not training:
        return x
    keep_prob = 1 - drop_prob
    shape = (x.shape[0],) + (1,) * (x.ndim - 1)  # work with diff dim tensors, not just 2D ConvNets
    random_tensor = x.new_empty(shape).bernoulli_(keep_prob)
    if keep_prob > 0.0 and scale_by_keep:
        random_tensor.div_(keep_prob)
    return x * random_tensor


class DropPath(nn.Module):
    """Drop paths (Stochastic Depth) per sample  (when applied in main path of residual blocks).
    """
    def __init__(self, drop_prob=None, scale_by_keep=True):
        super().__init__()
        self.drop_prob = drop_prob
        self.scale_by_keep = scale_by_keep

    def forward(self, x):
        return drop_path(x, self.drop_prob, self.training, self.scale_by_keep)

class RMSNorm(nn.Module):
    def __init__(self, dim: int, eps: float = 1e-6):
        super().__init__()
        self.eps = eps
        self.weight = nn.Parameter(torch.ones(dim))
    def forward(self, x: torch.Tensor):
        # 计算每个样本的均方根
        norm = (x.pow(2).mean(-1, keepdim=True) + self.eps).rsqrt()
        return x * (self.weight * norm)
    
def sinkhorn_knopp(matrix: torch.Tensor, num_iter: int = 20, epsilon: float = 1e-20) -> torch.Tensor:
    """
    Sinkhorn-Knopp 算法，将矩阵投影至双随机矩阵流形。
    双随机矩阵满足：所有行和为1，所有列和为1，且元素非负。
    
    参数:
        matrix: 输入矩阵，形状为 [batch_size, n, n]
        num_iter: 迭代次数，mHC论文中推荐20次【turn0search2】【turn0search5】
        epsilon: 防止除零的小常数，保证数值稳定性
        
    返回:
        双随机矩阵，形状与输入相同
    """
    # 确保输入矩阵非负（通常先经过指数化）
    # 减去最大值防止 exp 爆炸（Log-Sum-Exp 技巧的变体）
    matrix = torch.nan_to_num(matrix, nan=0.0, posinf=0.0, neginf=0.0)
    matrix = matrix - torch.max(matrix, dim=-1, keepdim=True)[0]
    K = torch.exp(matrix)
    for _ in range(num_iter):
        # 行归一化，使每行和为1
        K = K / (K.sum(dim=-1, keepdim=True) + epsilon)
        # 列归一化，使每列和为1
        K = K / (K.sum(dim=-2, keepdim=True) + epsilon)
    return K

def init_transformer_weights(module: nn.Module) -> None:
    # --- HyperConnection 模块的初始化检查 ---    
    if isinstance(module, HyperConnection):        
        # 确保动态映射的缩放因子保持为论文推荐的小值 (0.01)        
        # 防止被其他初始化逻辑（如 trunc_normal_）错误覆盖        
        if hasattr(module, 'dynamic_alpha_scale'):
            nn.init.constant_(module.dynamic_alpha_scale, 0.01)        
        if hasattr(module, 'dynamic_beta_scale'):
            nn.init.constant_(module.dynamic_beta_scale, 0.01)        
        return
    if isinstance(module, nn.Linear):
        trunc_normal_(module.weight, std=0.02)
        if module.bias is not None:
            nn.init.zeros_(module.bias)
        return

    if isinstance(module, nn.Embedding):
        trunc_normal_(module.weight, std=0.02)
        if module.padding_idx is not None:
            with torch.no_grad():
                module.weight[module.padding_idx].fill_(0)
        return

    if isinstance(module, nn.Conv2d):
        trunc_normal_(module.weight, std=0.02)
        if module.bias is not None:
            nn.init.zeros_(module.bias)
        return

    if isinstance(module, RMSNorm):
        nn.init.ones_(module.weight)
        return

    if isinstance(module, nn.LayerNorm):
        if module.weight is not None:
            nn.init.ones_(module.weight)
        if module.bias is not None:
            nn.init.zeros_(module.bias)
        return

    if isinstance(module, nn.MultiheadAttention):
        if getattr(module, 'in_proj_weight', None) is not None:
            trunc_normal_(module.in_proj_weight, std=0.02)
        else:
            if getattr(module, 'q_proj_weight', None) is not None:
                trunc_normal_(module.q_proj_weight, std=0.02)
            if getattr(module, 'k_proj_weight', None) is not None:
                trunc_normal_(module.k_proj_weight, std=0.02)
            if getattr(module, 'v_proj_weight', None) is not None:
                trunc_normal_(module.v_proj_weight, std=0.02)

        if getattr(module, 'in_proj_bias', None) is not None:
            nn.init.zeros_(module.in_proj_bias)
        if getattr(module, 'out_proj', None) is not None:
            trunc_normal_(module.out_proj.weight, std=0.02)
            if module.out_proj.bias is not None:
                nn.init.zeros_(module.out_proj.bias)
        if getattr(module, 'bias_k', None) is not None:
            nn.init.zeros_(module.bias_k)
        if getattr(module, 'bias_v', None) is not None:
            nn.init.zeros_(module.bias_v)
        return

# ------------------------------------------------------------------------------------
# 1. 核心模块：HyperConnection (完全修正的 mHC 版本)
# ------------------------------------------------------------------------------------
class SumToOne(nn.Module):
    def __init__(self, scale=3.5):
        super(SumToOne, self).__init__()
        self.scale = scale

    def forward(self, x):
        x = torch.softmax(x, dim=1)
        return x
    
class HyperConnection(nn.Module):
    """
    Hyper-Connection 模块 (mHC版本).
    
    该模块取代了传统的残差连接，包含宽度连接（width connection）和
    深度连接（depth connection）两个步骤。
    
    可以选择使用动态模式（DHC），其中连接权重是根据输入动态生成的。
    mHC 升级核心：
    1. 对 H_pre 和 H_post 应用非负约束 (Sigmoid)
    2. 对 H_res 应用 Sinkhorn-Knopp 投影至双随机流形
    3. 动态映射输入采用 Flattening 而非 Mean
    4. 最终输出采用 Mean 聚合而非 Sum
    """
    def __init__(self, dim: int, rate: int, layer_id: int, dynamic: bool = True, device=None):
        super().__init__()
        self.dim = dim
        self.rate = rate
        self.layer_id = layer_id
        self.dynamic = dynamic
        self.num_queries_times = 30
        self.num_endm = self.rate
        
        # --- 静态映射初始化 ---
        # 论文建议：静态映射在初始化时应接近恒等映射或均匀分布
        # 对于 H_res: 单位矩阵是恒等映射的初始化
        init_H_res = torch.eye(rate, device=device)
        # 对于 H_pre: [1, 0, 0, ..., 0] 对应保留第0个流作为层输入
        init_H_pre = torch.zeros(rate, 1, device=device)
        init_H_pre[0, 0] = 1.0
        # 拼接为 static_alpha: [rate, rate + 1]
        self.static_alpha = nn.Parameter(torch.cat([init_H_pre, init_H_res], dim=1))
        # 对于 H_post (beta): 初始化为均匀分布 [1/rate, 1/rate, ..., 1/rate]
        self.static_beta = nn.Parameter(torch.ones(rate, device=device) / rate)
        self.num_queries = self.num_queries_times * self.num_endm
        self.query_embed = nn.Embedding(self.num_queries, 200)
        self.weights = nn.Parameter(torch.ones((self.num_endm, self.num_queries_times)))
        self.abundance_constrain = SumToOne(scale=3.5)
        if self.dynamic:
            self.layer_norm = RMSNorm(dim)
            # --- 关键修正点1: 动态映射输入采用 Flattening (论文公式7) ---
            # 输入维度应为 rate * dim (Flattened)，以保留完整的上下文信息
            self.dynamic_alpha_fn = nn.Linear(rate * dim, rate * (rate + 1))
            self.dynamic_beta_fn = nn.Linear(rate * dim, rate)
            
            # 论文 A.1 提到 gating factor 初始化为小值 (0.1)
            self.dynamic_alpha_scale = nn.Parameter(torch.full((1,), 0.1))
            self.dynamic_beta_scale = nn.Parameter(torch.full((1,), 0.1))

    def width_connection(self, h: torch.Tensor):
        B, L, N, D = h.shape # [B, L, rate, dim]
        if self.dynamic:
            norm_h = self.layer_norm(h) # [B, L, N, D]
            # --- 关键修正点2: 按照论文公式(7)进行 Flatten ---
            agg_h = norm_h.view(B, L, -1) # [B, L, rate*dim]
            
            dyn_alpha = torch.tanh(self.dynamic_alpha_fn(agg_h)).view(B, L, self.rate, self.rate + 1)
            dyn_beta = torch.tanh(self.dynamic_beta_fn(agg_h)).view(B, L, self.rate)
            
            # 应用 gating scale 并与静态部分相加
            alpha = self.static_alpha + dyn_alpha * self.dynamic_alpha_scale
            beta = self.static_beta + dyn_beta * self.dynamic_beta_scale
        else:
            alpha = self.static_alpha.expand(B, L, -1, -1)
            beta = self.static_beta.expand(B, L, -1)

        # --- mHC 核心约束开始 ---
        # 拆分 alpha: [B, L, rate, rate+1] -> H_pre_raw [B, L, rate, 1], H_res_raw [B, L, rate, rate]
        H_pre_raw = alpha[..., :1]      # [B, L, rate, 1]
        H_res_raw = alpha[..., 1:]      # [B, L, rate, rate]
        x_diag = torch.diagonal(H_res_raw, dim1=2, dim2=3)
        #reshape_H_res = x_diag.reshape(B, 145, 145, N).permute(0, 3, 1, 2)
        #abundance = self.abundance_constrain(reshape_H_res)
        # --- 关键修正点3: H_pre 的非负约束 (论文公式8) ---
        H_pre = torch.sigmoid(H_pre_raw)
        
        # --- 关键修正点4: H_res 的 Sinkhorn 投影至双随机流形 ---
        # 注意：sinkhorn_knopp 内部通常包含 exp，所以输入不需要提前 exp
        # 但论文公式(9)确实写为 M(0) = exp(H~_res)
        # 我们的 sinkhorn_knopp 实现会处理这个 exp
        H_res = sinkhorn_knopp(H_res_raw, num_iter=20, epsilon=1e-12)
        # print(f"H_res {H_res}")
        # print(f"shape H_res {H_res.shape}")
        
        # --- 关键修正点5: H_post (beta) 的非负约束 (论文公式8) ---
        # 论文公式(8)明确指出 H_post = 2 * sigmoid(~H_post)
        beta_constrained = 2.0 * torch.sigmoid(beta)
        # reshape_beta = beta.reshape(B, 145, 145, N).permute(0, 3, 1, 2)
        # abundance = self.abundance_constrain(reshape_beta)
        # --- mHC 核心约束结束 ---

        # 应用 H_pre 和 H_res
        # h: [B, L, rate, dim]
        # h_for_layer: H_pre^T @ h -> [B, L, 1, dim]
        h_for_layer = torch.matmul(H_pre.transpose(-2, -1), h)
        # h_res_flow: H_res^T @ h -> [B, L, rate, dim]
        h_res_flow = torch.matmul(H_res.transpose(-2, -1), h)
        
        # 拼接: mix_h[..., 0, :] 是给 Layer F 的输入，mix_h[..., 1:, :] 是残差流
        mix_h = torch.cat([h_for_layer, h_res_flow], dim=-2) # [B, L, rate+1, dim]
        
        return mix_h, beta_constrained, H_res, H_pre

    def depth_connection(self, mix_h: torch.Tensor, h_o: torch.Tensor, beta: torch.Tensor) -> torch.Tensor:
        # mix_h: [B, L, rate+1, dim]
        h_prime = mix_h[..., 1:, :] # [B, L, rate, dim] - 残差流部分
        # h_o: Layer F 的输出 [B, L, dim]
        # 对应论文公式(3): x^{l+1} = H_res^l x^l + (H_post^l)^T F(...)
        # h_o_weighted: (H_post^l)^T F(...) -> [B, L, rate, dim]
        h_o_weighted = torch.einsum('bld,bln->blnd', h_o, beta)
        return h_prime + h_o_weighted

# ------------------------------------------------------------------------------------
# 2. 文本模型构建块 
# ------------------------------------------------------------------------------------

class FeedForward(nn.Module):
    def __init__(self, dim: int, hidden_dim: int):
        super().__init__()
        self.net = nn.Sequential(nn.Linear(dim, hidden_dim), nn.GELU(), nn.Linear(hidden_dim, dim))
    def forward(self, x):
        return self.net(x)

class HyperConnectionBlock(nn.Module):
    def __init__(self, dim: int, n_heads: int, rate: int, layer_id: int, dropout: float = 0.1):
        super().__init__()
        # 使用 RMSNorm 替换原有的 LayerNorm，实现 Pre-Norm 结构
        self.attn_norm = RMSNorm(dim)
        self.ffn_norm = RMSNorm(dim)
        self.attention = nn.MultiheadAttention(dim, n_heads, dropout=dropout, batch_first=True)
        self.ffn = FeedForward(dim, dim * 4)
        self.attn_hc = HyperConnection(dim, rate, layer_id, dynamic=True)
        self.ffn_hc = HyperConnection(dim, rate, layer_id, dynamic=True)
        self.attn_dropout = nn.Dropout(dropout)
        self.ffn_dropout = nn.Dropout(dropout)

    def forward(self, h: torch.Tensor, mask=None) -> torch.Tensor:
        mix_h_attn, beta_attn = self.attn_hc.width_connection(h)
        h_in_attn = self.attn_norm(mix_h_attn[..., 0, :])
        attn_output, _ = self.attention(h_in_attn, h_in_attn, h_in_attn, attn_mask=mask)
        h = self.attn_hc.depth_connection(mix_h_attn, self.attn_dropout(attn_output), beta_attn)
        mix_h_ffn, beta_ffn = self.ffn_hc.width_connection(h)
        h_in_ffn = self.ffn_norm(mix_h_ffn[..., 0, :])
        ffn_output = self.ffn(h_in_ffn)
        h = self.ffn_hc.depth_connection(mix_h_ffn, self.ffn_dropout(ffn_output), beta_ffn)
        return h

"""文本模型块：TextHyperConnectionBlock，使用 nn.MultiheadAttention"""
class TextHyperConnectionBlock(nn.Module):
    def __init__(self, dim: int, n_heads: int, rate: int, layer_id: int, dropout: float = 0.1):
        super().__init__()
        self.attn_norm = RMSNorm(dim)
        self.ffn_norm = RMSNorm(dim)
        self.attention = nn.MultiheadAttention(dim, n_heads, dropout=dropout, batch_first=True)
        self.ffn = FeedForward(dim, dim * 4)
        self.attn_hc = HyperConnection(dim, rate, layer_id, dynamic=True)
        self.ffn_hc = HyperConnection(dim, rate, layer_id, dynamic=True)
        self.attn_dropout = nn.Dropout(dropout)
        self.ffn_dropout = nn.Dropout(dropout)

    def forward(self, h: torch.Tensor, mask=None) -> torch.Tensor:
        mix_h_attn, beta_attn = self.attn_hc.width_connection(h)
        h_in_attn = self.attn_norm(mix_h_attn[..., 0, :])
        attn_output, _ = self.attention(h_in_attn, h_in_attn, h_in_attn, attn_mask=mask)
        h = self.attn_hc.depth_connection(mix_h_attn, self.attn_dropout(attn_output), beta_attn)
        mix_h_ffn, beta_ffn = self.ffn_hc.width_connection(h)
        h_in_ffn = self.ffn_norm(mix_h_ffn[..., 0, :])
        ffn_output = self.ffn(h_in_ffn)
        h = self.ffn_hc.depth_connection(mix_h_ffn, self.ffn_dropout(ffn_output), beta_ffn)
        return h

# ------------------------------------------------------------------------------------
# 3. 文本模型
# ------------------------------------------------------------------------------------

class HyperConnectionTransformer(nn.Module):
    def __init__(self, vocab_size: int, max_len: int, dim: int, 
        n_layers: int, n_heads: int, rate: int, dropout: float = 0.1, drop_path: float = 0.0,
        return_hidden: bool = False):
        super().__init__()
        if dim % 2 != 0:
            raise ValueError(f"dim must be even for SinusoidalPositionEncoding, got {dim}")
        self.expansion_rate = rate
        self.token_embedding = nn.Embedding(vocab_size, dim)
        self.pos_encoding = SinusoidalPositionEncoding(d_model=dim, max_len=max_len)
        self.emb_dropout = nn.Dropout(dropout)
        self.max_len = max_len
        self.return_hidden = return_hidden

        self.layers = nn.ModuleList([
            TextHyperConnectionBlock(
                dim, n_heads, rate, layer_id, dropout
            ) for layer_id in range(n_layers)
        ])
        if n_layers > 0 and drop_path > 0.0:
            dpr = torch.linspace(0, drop_path, n_layers).tolist()
        else:
            dpr = [0.0 for _ in range(n_layers)]
        self.drop_paths = nn.ModuleList([
            DropPath(dpr[layer_id]) if dpr[layer_id] > 0.0 else nn.Identity()
            for layer_id in range(n_layers)
        ])
        self.final_norm = RMSNorm(dim)  # 替换 nn.LayerNorm(dim)
        self.lm_head = nn.Linear(dim, vocab_size) if not return_hidden else nn.Identity()
        self.apply(init_transformer_weights)

    def forward(self, idx: torch.Tensor, mask=None):
        B, L = idx.shape; device = idx.device
        tok_emb = self.token_embedding(idx)
        positions = torch.arange(0, L, device=device, dtype=torch.float32).unsqueeze(0)
        pos_emb = self.pos_encoding(positions).to(dtype=tok_emb.dtype)
        h = self.emb_dropout(tok_emb + pos_emb)
        H = h.unsqueeze(2).repeat(1, 1, self.expansion_rate, 1)
        for layer, dp in zip(self.layers, self.drop_paths):
            H = dp(layer(H, mask=mask))
        h_final = H.mean(dim=2)
        h_final = self.final_norm(h_final)
        logits = self.lm_head(h_final)
        return logits

# ------------------------------------------------------------------------------------
# 5. 图像模型构建块
# ------------------------------------------------------------------------------------

class ImageHyperConnectionBlock(nn.Module):
    def __init__(self, dim: int, n_heads: int, rate: int, layer_id: int, dropout: float = 0.1, dynamic: bool = False):
        super().__init__()
        self.dynamic = dynamic
        self.attn_norm = RMSNorm(dim)
        self.ffn_norm = RMSNorm(dim)
        self.attention = nn.MultiheadAttention(dim, n_heads, dropout=dropout, batch_first=True)
        # self.spatial_branch = Mamba(
        #     d_model=dim,
        #     d_state=16,
        #     d_conv=4,
        #     expand=2,
        # )
        self.spectral_branch = Mamba(
            d_model=dim//rate,
            d_state=16,
            d_conv=4,
            expand=2,
        )
        self.spatial_adpative_clustering_branch = nn.ModuleList([
            Mamba(
                d_model=dim,
                d_state=16,
                d_conv=4,
                expand=2,
            ) for _ in range(rate**2)
        ])
        self.ffn = FeedForward(dim, dim * 4)
        self.attn_hc = HyperConnection(dim, rate, layer_id, dynamic=self.dynamic)
        self.ffn_hc = HyperConnection(dim, rate, layer_id, dynamic=self.dynamic)
        self.attn_dropout = nn.Dropout(dropout)
        self.ffn_dropout = nn.Dropout(dropout)

    def forward(self, h: torch.Tensor, mask=None) -> torch.Tensor:
        mix_h_attn, beta_attn, alpha, H_pre = self.attn_hc.width_connection(h)
        h_in_attn = self.attn_norm(mix_h_attn[..., 0, :])

        B, HW, C = h_in_attn.shape
        rate = alpha.shape[-1]
        # -----------------------------
        # Prepare clustering scores
        # -----------------------------
        B, HW, C = h_in_attn.shape
        H, W = 145, 145
        x_flat = h_in_attn.view(B * HW, rate, C//rate)
        clustering = alpha.reshape(B, HW, -1)
        selected_indices = []
        cluster_num = alpha.shape[2]*alpha.shape[3]
        k = int(0.1 * HW)
        for cluster_idx in range(cluster_num):
            cluster_scores = clustering[:, :, cluster_idx]
            _, topk_indices = torch.topk(cluster_scores, k=k, dim=-1)
            selected_indices.append(topk_indices)
        x_flat = self.spectral_branch(x_flat)
        attn_output = x_flat.view(B, HW, C)
        output = torch.zeros(B, HW, C, device=attn_output.device)
        x_processed = []
        x_processed.extend(
            self.spatial_adpative_clustering_branch[i](attn_output[:, selected_indices[i][0], :])
            for i in range(cluster_num)
        )
        for i in range(cluster_num):
            output.scatter_add_(1,selected_indices[i][0].unsqueeze(dim=0).unsqueeze(-1).expand(-1, -1, C),x_processed[i])
        # normalize repeated selections
        #output = output / (count + 1e-6)
        #output = output + attn_output
        # residual connection
        # out = output.view(B*HW, 4, C//4)
        # spe_output = self.spectral_branch(out)
        # spe_output = spe_output.view(B, HW, -1)
        h = self.attn_hc.depth_connection(mix_h_attn, self.attn_dropout(output), beta_attn)
        mix_h_ffn, beta_ffn, alpha, H_pre = self.ffn_hc.width_connection(h)
        h_in_ffn = self.ffn_norm(mix_h_ffn[..., 0, :])
        ffn_output = self.ffn(h_in_ffn)
        # endm_get = self.get_endmember()
        # recon_linear = torch.einsum('brhw,rl->blhw', [abundance, endm_get])
        h = self.ffn_hc.depth_connection(mix_h_ffn, self.ffn_dropout(ffn_output), beta_ffn)
        return h, alpha, beta_ffn, H_pre

    def get_endmember(self):
        query_embed_weight_split = torch.chunk(self.ffn_hc.query_embed.weight, self.ffn_hc.num_endm, dim=0)
        query_embed_weight_split = torch.stack(query_embed_weight_split)
        endmember_get = self.ffn_hc.weights.unsqueeze(-1).repeat(1, 1, 200) * query_embed_weight_split
        endmember_get = torch.mean(endmember_get, dim=1)
        return endmember_get

# ------------------------------------------------------------------------------------
# 6. 图像模型 
# ------------------------------------------------------------------------------------

class My_Loss(nn.Module):
    def __init__(self, weight_mse=1.0, weight_sad=1.0, weight_endm=0.001, weight_aban=1e-6):
        super(My_Loss, self).__init__()
        self.weight_mse = weight_mse
        self.weight_sad = weight_sad
        self.weight_endm = weight_endm
        self.weight_aban = weight_aban
        self.SAD = SADLoss()
        self.MSE = nn.MSELoss()

    def forward(self, y_true, y_pred, endm=None, hsi_mean=None, pred_aban=None):
        loss = 0
        if self.weight_mse != 0:
            loss += self.weight_mse * self.MSE(y_true, y_pred)

        if 1 < len(y_pred.shape) < 5:
            y_true = y_true.view(y_true.shape[0], y_true.shape[1], -1).transpose(1, 2)
            y_pred = y_pred.reshape(y_pred.shape[0], y_pred.shape[1], -1).transpose(1, 2)
        elif len(y_pred.shape) >= 5:
            y_true = rearrange(y_true, 'n b c w h -> (n b) (w h) c')
            y_pred = rearrange(y_pred, 'n b c w h -> (n b) (w h) c')

        if self.weight_sad != 0:
            loss_sad = self.weight_sad * self.SAD(y_true, y_pred)
            loss += loss_sad
        if endm is not None and hsi_mean is not None and self.weight_endm != 0:
            loss += self.weight_endm * self.MSE(hsi_mean, endm)
        if pred_aban is not None:
            aban_norm = torch.norm(pred_aban, p=0.5, dim=1)
            loss_aban = self.weight_aban * aban_norm.mean()
            loss += loss_aban
        return loss
    
class ImageHyperConnectionTransformer(nn.Module):
    def __init__(self, image_size: int, patch_size: int, in_channels: int, num_classes: int, 
                 dim: int, n_layers: int, n_heads: int, rate: int, dropout: float = 0.1, drop_path: float = 0,
                 pool_size=4, mask_ratio=0.1, dynamic=True, wavelengths=None):
        super().__init__()
        if dim % 2 != 0:
            raise ValueError(f"dim must be even for SinusoidalPositionEncoding, got {dim}")
        if type(image_size)==int: image_size = (image_size, image_size)
        if type(patch_size)==int: patch_size = (patch_size, patch_size)
        if type(pool_size)==int: pool_size = (pool_size, pool_size)
        # self.expansion_rate = rate
        self.patch_size = patch_size
        self.width = image_size[1] // patch_size[1]
        self.height = image_size[0] // patch_size[0]
        self.num_patches = self.width * self.height
        self.dynamic = dynamic
        self.mseloss = nn.MSELoss(reduction='mean')   # sum instead of mean
        self.num_layers = n_layers
        assert wavelengths is not None, "wavelengths must be provided for physics grouping"
        self.wavelengths = torch.tensor(wavelengths, dtype=torch.float32)
        # self.band_groups = self._build_band_groups()
        # self.num_streams = len(self.band_groups)
        # self.num_groups = len(self.band_groups)
        # self.substreams_per_group = 2   # default
        # self.expansion_rate = self.num_groups * self.substreams_per_group
        # rate = self.expansion_rate
        self.dim = dim
        vis_idx   = torch.where((self.wavelengths >= 400) & (self.wavelengths < 700))[0]
        nir_idx   = torch.where((self.wavelengths >= 700) & (self.wavelengths < 1000))[0]
        swir1_idx = torch.where((self.wavelengths >= 1000) & (self.wavelengths < 1800))[0]
        swir2_idx = torch.where((self.wavelengths >= 1800) & (self.wavelengths <= 2500))[0]
        full_idx  = torch.arange(self.wavelengths.numel())
        self.band_groups = {
            "FULL":  full_idx,   # all bands
            "VIS":   vis_idx,
            "NIR":   nir_idx,
            "SWIR1": swir1_idx,
            "SWIR2": swir2_idx,
        }
        self.expansion_rate = len(self.band_groups)  # = 5


        pos_dim = dim // 2
        self.pos_y = SinusoidalPositionEncoding(d_model=pos_dim, max_len=self.height)
        self.pos_x = SinusoidalPositionEncoding(d_model=pos_dim, max_len=self.width)
        pos_y = torch.arange(self.height, dtype=torch.float32).unsqueeze(1).repeat(1, self.width)
        pos_x = torch.arange(self.width, dtype=torch.float32).unsqueeze(0).repeat(self.height, 1)
        pos_y = pos_y.flatten().unsqueeze(0)
        pos_x = pos_x.flatten().unsqueeze(0)
        pos_embed = torch.cat([self.pos_y(pos_y), self.pos_x(pos_x)], dim=-1)
        self.register_buffer('pos_embed', pos_embed, persistent=False)
        self.patch_embeds = nn.ModuleDict({
            name: nn.Conv2d(
                in_channels=len(idx),
                out_channels=self.dim,
                kernel_size=self.patch_size,
                stride=self.patch_size
            )
            for name, idx in self.band_groups.items()
        })
        #self.patch_embed = nn.Conv2d(in_channels, dim, kernel_size=patch_size, stride=patch_size)
        self.emb_dropout = nn.Dropout(dropout)

        self.layers = nn.ModuleList([
            ImageHyperConnectionBlock(
                dim, n_heads, self.expansion_rate, layer_id, dropout, dynamic=self.dynamic
            ) for layer_id in range(n_layers)])

        if n_layers > 0 and drop_path > 0:
            dpr = torch.linspace(0, drop_path, n_layers).tolist()
        else:
            dpr = [0.0 for _ in range(n_layers)]
        self.drop_paths = nn.ModuleList([
            DropPath(dpr[layer_id]) if dpr[layer_id] > 0.0 else nn.Identity()
            for layer_id in range(n_layers)
        ])
        self.final_norm = RMSNorm(dim)
        self.classifier = nn.Linear(dim, num_classes)
        self.pool1 = nn.MaxPool2d(kernel_size=2, stride=2, padding=0)   
        self.cls_head = nn.Sequential(nn.Conv2d(in_channels=dim, out_channels=dim*2, kernel_size=1),
                                      #RMSNorm(dim*2),
                                      nn.GroupNorm(self.expansion_rate, dim*2),
                                      nn.SiLU(),
                                      nn.Conv2d(in_channels=dim*2,out_channels=num_classes,kernel_size=1))
        self.pool_size = pool_size
        self.mask_ratio = mask_ratio
        self.apply(init_transformer_weights)
        
    def _build_band_groups(self):
        wl = self.wavelengths

        groups = {
            "VIS":   (wl >= 400) & (wl < 700),
            "NIR":   (wl >= 700) & (wl < 1000),
            "SWIR1": (wl >= 1000) & (wl < 1800),
            "SWIR2": (wl >= 1800) & (wl <= 2500),
        }

        band_groups = {
            name: torch.where(mask)[0]
            for name, mask in groups.items()
            if mask.any()
        }
        return band_groups

    def random_masking(self, x, mask_ratio=0.1):
        """
        Perform per-sample random masking by per-sample shuffling.
        Per-sample shuffling is done by argsort random noise.
        x: [N, L, D], sequence
        """
        N, L, D = x.size()  # batch, length, dim
        len_keep = int(L * (1 - mask_ratio))

        noise = torch.rand(N, L, device=x.device)  # noise in [0, 1]

        # sort noise for each sample
        # ascend: small is keep, large is remove
        ids_shuffle = torch.argsort(noise, dim=1)
        ids_restore = torch.argsort(ids_shuffle, dim=1)

        # keep the first subset
        ids_keep = ids_shuffle[:, :len_keep]
        x_masked = torch.gather(
            x, dim=1, index=ids_keep.unsqueeze(-1).repeat(1, 1, D))

        # generate the binary mask: 0 is keep, 1 is remove
        mask = torch.ones([N, L], device=x.device)
        mask[:, :len_keep] = 0
        # unshuffle to get the binary mask
        mask = torch.gather(mask, dim=1, index=ids_restore)

        return x_masked, mask, ids_restore
    def forward(self, x: torch.Tensor, gt_Map=None, epoch=None, return_features=False):
        """
        x: (B, C, H, W)  hyperspectral image
        """

        hsi = x
        B = x.shape[0]

        stream_feats = []   # will store (B, L, k_g, dim) for each group
        for name, idx in self.band_groups.items():
            x_g = x[:, idx, :, :]                 # (B, Cg, H, W)
            x_g = self.patch_embeds[name](x_g)    # (B, dim, Hp, Wp). 320
            x_g = x_g.flatten(2).transpose(1, 2)  # (B, L, dim) 
            if name == "FULL":
                x_g = x_g + self.pos_embed
            x_g = self.emb_dropout(x_g)
            stream_feats.append(x_g)

        H = torch.stack(stream_feats, dim=2)      # (B, L, 5, dim). 

        B, L, N, C = H.shape
        Y = []
        spatial_regularized_loss = 0.
        for layer, dp in zip(self.layers, self.drop_paths):
            H, alpha, beta_ffn, H_pre = dp(layer(H))
            y = H.mean(dim=2).permute(0, 2, 1).contiguous()  # (B, C, L_keep or L)
            if self.mask_ratio == 0 or not self.training or ids_restore is None:
                Y.append(y.view(B, C, self.width, self.height))
            else:
                # 重建被 mask 前的 full-length token 序列，并填充到对应位置
                len_keep = y.shape[-1]
                L_full = self.num_patches
                ids_shuffle = torch.argsort(ids_restore, dim=1)          # (B, L_full)
                ids_keep = ids_shuffle[:, :len_keep]                      # (B, len_keep)
                y_full = torch.zeros(B, C, L_full, device=y.device, dtype=y.dtype)
                y_full.scatter_(2, ids_keep.unsqueeze(1).expand(-1, C, -1), y)
                Y.append(y_full.view(B, C, self.width, self.height))
        
        if epoch is not None:
            if (epoch+1) % 20 == 0:
                H_res_matrix, gt = prepare_inputs(alpha[0], gt_Map, ignore_label=0)
                auc_results = auc_analysis_all_classes(H_res_matrix, gt)

                stream_names = ["FULL", "VIS", "NIR", "SWIR1", "SWIR2"]
                for class_id in range(16):
                    plot_auc_heatmap(
                        auc_results[class_id+1],
                        class_id=class_id,
                        stream_names=stream_names
                    )
                
                class_means = compute_class_means(
                                H_res_matrix, gt,
                                num_classes=16,
                                ignore_label=0
                            )

                plot_all_interaction_bars(
                            class_means,
                            stream_names=stream_names,
                            normalize=True,
                            save_dir="./bars/"   # or "./bars/"
                        )
                
                # plot_all_Hres_boundaries(
                #     H_res=alpha[0].detach().cpu().numpy(),
                #     gt_map=gt_Map.reshape(145, 145),
                #     class_means=class_means,
                #     stream_names=stream_names,
                #     save_dir="./Hres_boundaries"   # or None to display
                # )
                
                plot_all_Hres_boundaries_single_figure(
                    H_res=alpha[0].detach().cpu().numpy(),
                    gt_map=gt_Map.reshape(145, 145),
                    class_means=class_means,
                    stream_names=["FULL", "VIS", "NIR", "SWIR1", "SWIR2"],
                    save_path="Hres_boundary_grid.png"
                )



        # if epoch is not None:
        #     if (epoch+1) % 10 == 0:
        #         plot_16_hist2d(alpha.detach().cpu().numpy()[0].reshape(145**2, self.expansion_rate*self.expansion_rate), epoch)
        #         plot_16_H_res(alpha.detach().cpu().numpy().reshape(1, 145, 145, self.expansion_rate*self.expansion_rate), epoch+1, beta_ffn, H_pre, self.expansion_rate)
        
        #         for ii in range(self.expansion_rate):
        #             for jj in range(self.expansion_rate):
        #                 fig = plt.figure()
        #                 plt.imshow(alpha.detach().cpu().numpy()[0, :, ii, jj].reshape(145, 145))
        #                 plt.axis("off")
        #                 plt.tight_layout()
        #                 fig.savefig(f"./maps/abudance_res_branch{ii+1}_branch{jj+1}_epoch_{epoch}.png", bbox_inches="tight")
        #                 plt.close(fig)
        
        # if epoch is not None:
        #     if (epoch+1) % 10 == 0:
        #         for jj in range(self.expansion_rate):
        #             fig = plt.figure()
        #             plt.imshow(beta_ffn.detach().cpu().numpy()[0, :, jj].reshape(145, 145))
        #             plt.axis("off")
        #             plt.tight_layout()
        #             fig.savefig(f"./maps/abudance_post_branch_branch{jj+1}_epoch_{epoch}.png", bbox_inches="tight")
        #             plt.close(fig)
                    
        #             fig = plt.figure()
        #             plt.imshow(H_pre.detach().cpu().numpy()[0, :, jj, 0].reshape(145, 145))
        #             plt.axis("off")
        #             plt.tight_layout()
        #             fig.savefig(f"./maps/abudance_pre_branch_branch{jj+1}_epoch_{epoch}.png", bbox_inches="tight")
        #             plt.close(fig)   
        #weights = beta_ffn.unsqueeze(-1)
        #h_final = (H * weights).mean(dim=2)  # (B, L_keep or L_full, C)
        h_final = H.mean(dim=2)
        #h_final = H.view(B, L, -1)
        # 如果使用了 masking，则需要先用 ids_restore 还原到 full-length，再做空间 reshape
        if self.training and self.mask_ratio > 0 and ids_restore is not None:
            y_tokens = h_final.permute(0, 2, 1).contiguous()  # (B, C, L_keep)
            len_keep = y_tokens.shape[-1]
            L_full = self.num_patches
            ids_shuffle = torch.argsort(ids_restore, dim=1)      # (B, L_full)
            ids_keep = ids_shuffle[:, :len_keep]                  # (B, len_keep)
            y_full = torch.zeros(B, C, L_full, device=y_tokens.device, dtype=y_tokens.dtype)
            y_full.scatter_(2, ids_keep.unsqueeze(1).expand(-1, C, -1), y_tokens)
            h_final = y_full.permute(0, 2, 1).contiguous()        # (B, L_full, C)

        h_final = self.final_norm(h_final)
        B, C = h_final.shape[0], h_final.shape[-1]
        h_final = h_final.view(B, self.height, self.width, C).permute(0, 3, 1, 2).contiguous()
        logits = self.cls_head(h_final)
        Y.append(logits)
        if return_features: return Y
        return logits

# ------------------------------------------------------------------------------------
# 7. 解码器模型
# ------------------------------------------------------------------------------------

class HyperConnectionDecodeTransformer(nn.Module):
    """
    解码器结构的 HyperConnection Transformer（自回归）。
    - 不包含 KV cache（简单实现）。
    - 支持 past_len 参数来表示已有前缀长度，从而构建正确的因果掩码。
    """
    def __init__(self, vocab_size: int, max_len: int, dim: int, n_layers: int, 
        n_heads: int, rate: int, dropout: float = 0.1):
        super().__init__()
        if dim % 2 != 0:
            raise ValueError(f"dim must be even for SinusoidalPositionEncoding, got {dim}")
        self.expansion_rate = rate
        self.token_embedding = nn.Embedding(vocab_size, dim)
        self.pos_encoding = SinusoidalPositionEncoding(d_model=dim, max_len=max_len)
        self.emb_dropout = nn.Dropout(dropout)
        self.max_len = max_len

        self.layers = nn.ModuleList([
            TextHyperConnectionBlock(
                dim, n_heads, rate, layer_id, dropout
            ) for layer_id in range(n_layers)
        ])
        self.final_norm = RMSNorm(dim)
        self.lm_head = nn.Linear(dim, vocab_size)
        self.apply(init_transformer_weights)

    def _build_causal_mask(self, seq_len: int, past_len: int, device: torch.device):
        """
        构建自回归因果掩码：返回形状 (seq_len, total_k) 的布尔掩码，True 表示允许（attend），False 表示屏蔽。
        total_k = past_len + seq_len
        对于查询位置 i (0-based), 允许访问所有 past positions (j < past_len) 以及当前段中 j <= past_len + i
        """
        total_k = past_len + seq_len
        q_idx = torch.arange(seq_len, device=device).unsqueeze(1)  # (seq_len, 1)
        k_idx = torch.arange(total_k, device=device).unsqueeze(0)  # (1, total_k)
        allowed = (k_idx < past_len) | (k_idx <= (past_len + q_idx))
        # Convert to float mask with 1/0 for compatibility where code checks mask==0
        return allowed

    def forward(self, input_ids: torch.Tensor, past_len: int = 0, mask: torch.Tensor = None):
        
        
        """
        Args:
            input_ids: (batch, seq_len)
            past_len: int, 表示已存在的前缀长度（用于 causal mask）
            mask: 额外的注意力 mask，优先级叠加在因果掩码上
        Returns:
            logits: (batch, seq_len, vocab_size)
        """
        if self.training == True:
            B, L = input_ids.shape
            device = input_ids.device
            if past_len + L > self.max_len:
                raise ValueError(f"Input length + past_len ({past_len + L}) exceeds max_len ({self.max_len})")

            tok_emb = self.token_embedding(input_ids)
            positions = torch.arange(past_len, past_len + L, device=device, dtype=torch.float32).unsqueeze(0)
            pos_emb = self.pos_encoding(positions).to(dtype=tok_emb.dtype)
            h = self.emb_dropout(tok_emb + pos_emb)
            H = h.unsqueeze(2).repeat(1, 1, self.expansion_rate, 1)

            causal_mask = torch.triu(
                torch.ones(L, L, device=device, dtype=torch.bool),
                diagonal=1,
            )
            attn_mask = causal_mask

            for layer in self.layers:
                H = layer(H, mask=attn_mask)
            h_final = H.mean(dim=2)
            h_final = self.final_norm(h_final)
            logits = self.lm_head(h_final)
            return logits
        else:
            B, L = input_ids.shape
            device = input_ids.device
            if past_len + L > self.max_len:
                raise ValueError(f"Input length + past_len ({past_len + L}) exceeds max_len ({self.max_len})")

            tok_emb = self.token_embedding(input_ids)
            positions = torch.arange(past_len, past_len + L, device=device, dtype=torch.float32).unsqueeze(0)
            pos_emb = self.pos_encoding(positions).to(dtype=tok_emb.dtype)
            h = self.emb_dropout(tok_emb + pos_emb)
            H = h.unsqueeze(2).repeat(1, 1, self.expansion_rate, 1)

            causal_mask = torch.triu(
                torch.ones(L, L, device=device, dtype=torch.bool),
                diagonal=1,
            )
            attn_mask = causal_mask

            for layer in self.layers:
                H = layer(H, mask=attn_mask)
            h_final = H.mean(dim=2)
            h_final = self.final_norm(h_final)
            logits = self.lm_head(h_final)
            return logits
    

def plot_16_hist2d(X, e, bins=200):
    N, C = X.shape
    fig, axes = plt.subplots(5, 5, figsize=(20, 20))
    axes = axes.flatten()

    x = np.arange(N)

    for i in range(25):
        ax = axes[i]
        h = ax.hist2d(x, X[:, i], bins=bins)
        # ax.set_title(f"Stream {i+1}")
        # ax.set_xlabel("Pixel index")
        # ax.set_ylabel("Value")
        plt.colorbar(h[3], ax=ax)

    plt.tight_layout()
    plt.savefig(f"./scatter_plot/scatter_epoch_{e}.png", bbox_inches="tight")
    plt.close(fig)
    
    plot_all_12_nondiagonal_pairs(X, e)

def plot_16_H_res(X, e, beta_ffn, H_pre, rate):
    B, H, W, Num = X.shape
    fig, axes = plt.subplots(5, 5, figsize=(20, 20))
    axes = axes.flatten()
    for i in range(Num):
        ax = axes[i]
        h = ax.imshow(X[0, :, :, i])
        plt.colorbar(h, ax=ax)

    plt.tight_layout()
    plt.savefig(f"./matrix/H_res_{e}.png", bbox_inches="tight")
    plt.close(fig)
    
    fig, axes = plt.subplots(1, 5, figsize=(20, 5))
    axes = axes.flatten()
    for i in range(rate):
        ax = axes[i]
        tmp = beta_ffn.detach().cpu().numpy()[0, :, i].reshape(H, W)
        h = ax.imshow(tmp)
        plt.colorbar(h, ax=ax)

    plt.tight_layout()
    plt.savefig(f"./matrix/H_post_{e}.png", bbox_inches="tight")
    plt.close(fig)
    
    fig, axes = plt.subplots(1, 5, figsize=(20, 5))
    axes = axes.flatten()
    for i in range(rate):
        ax = axes[i]
        tmp = H_pre.detach().cpu().numpy()[0, :, i, 0].reshape(H, W)
        h = ax.imshow(tmp)
        plt.colorbar(h, ax=ax)

    plt.tight_layout()
    plt.savefig(f"./matrix/H_pre_{e}.png", bbox_inches="tight")
    plt.close(fig)
    
    # fig, axes = plt.subplots(1, 4, figsize=(16, 4))
    # axes = axes.flatten()
    # for i in range(rate):
    #     ax = axes[i]
    #     tmp = abundance.detach().cpu().numpy()[0, i, :, :]
    #     h = ax.imshow(tmp)
    #     plt.colorbar(h, ax=ax)

    # plt.tight_layout()
    # plt.savefig(f"./matrix/abudance_{e}.png", bbox_inches="tight")
    # plt.close(fig)
    
    
    
def plot_all_12_nondiagonal_pairs(X, e, S=5):
    """
    X: (N, 16) flattened 4x4 matrices
    """

    pairs = [(i, j) for i in range(S) for j in range(S) if i != j]

    fig, axes = plt.subplots(4, 5, figsize=(20, 16))
    axes = axes.flatten()

    for ax, (i, j) in zip(axes, pairs):
        idx_ij = i * S + j
        idx_ji = j * S + i

        x = X[:, idx_ij]
        y = X[:, idx_ji]

        scatter_density_xy(x, y, ax)

        ax.set_title(
            rf"$\mathcal{{H}}^{{\mathrm{{Res}}}}({i+1},{j+1})\;\text{{joint}}\;\mathcal{{H}}^{{\mathrm{{Res}}}}[{j+1},{i+1})$",
            fontsize=14
        )
        ax.set_xlabel(rf"$\mathcal{{H}}^{{\mathrm{{Res}}}}({i+1},{j+1})$")
        ax.set_ylabel(rf"$\mathcal{{H}}^{{\mathrm{{Res}}}}({j+1},{i+1})$")

        lims = [
            min(x.min(), y.min()),
            max(x.max(), y.max())
        ]
        ax.plot(lims, lims, "k--", alpha=0.5)
        ax.set_xlim(lims)
        ax.set_ylim(lims)
    plt.tight_layout()
    plt.savefig(f"./scatter_plot/off_diagonal_epoch_{e}.png", bbox_inches="tight")
    plt.close(fig)

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import gaussian_kde
from skimage.segmentation import find_boundaries

def get_class_boundary(gt_map, class_id):
    """
    gt_map: (H, W)
    returns: binary boundary mask (H, W)
    """
    class_mask = (gt_map == class_id)
    boundary = find_boundaries(class_mask, mode="outer")
    return boundary

import matplotlib.pyplot as plt
import numpy as np

def plot_all_Hres_boundaries_single_figure(
    H_res, gt_map, class_means,
    stream_names=None,
    class_names=None,
    cmap="viridis",
    save_path=None,
    percentile=(5, 95)   # robust scaling
):
    """
    Plot all H_res(i,j) in ONE figure with class boundary overlays.
    Each subplot uses its own color scale derived from its data.
    """

    L, N, _ = H_res.shape
    H, W = gt_map.shape
    assert L == H * W, "H_res must match spatial resolution (L = H*W)"

    fig, axes = plt.subplots(N, N, figsize=(3*N, 3*N))

    for i in range(N):
        for j in range(N):
            ax = axes[i, j]

            # spatial map
            H_map = H_res[:, i, j].reshape(H, W)

            # per-map color scaling
            vmin, vmax = np.percentile(H_map, percentile)

            # dominant class (GT is 1-based)
            class_idx = np.nanargmax(class_means[i, j])
            boundary = get_class_boundary(gt_map, class_idx)

            ax.imshow(H_map, cmap=cmap, vmin=vmin, vmax=vmax)
            ax.contour(boundary, colors="red", linewidths=0.8)

            if stream_names:
                ax.set_title(f"{stream_names[i]} → {stream_names[j]}", fontsize=9)
            else:
                ax.set_title(f"H({i},{j})", fontsize=9)

            ax.axis("off")

    fig.subplots_adjust(wspace=0.05, hspace=0.15)

    if save_path:
        plt.savefig(save_path, dpi=300, bbox_inches="tight")
        plt.close(fig)
    else:
        plt.show()




def scatter_density_xy(x, y, ax, s=4):
    xy = np.vstack([x, y])
    z = gaussian_kde(xy)(xy)

    idx = z.argsort()
    x, y, z = x[idx], y[idx], z[idx]

    sc = ax.scatter(x, y, c=z, s=s)
    return sc


import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import roc_auc_score

def prepare_inputs(H_res, gt_map, ignore_label=None):
    if hasattr(H_res, "detach"):
        H_res = H_res.detach().cpu().numpy()

    if gt_map.ndim == 2:
        gt = gt_map.reshape(-1)
    else:
        gt = gt_map.copy()

    if ignore_label is not None:
        valid_mask = gt != ignore_label
        H_res = H_res[valid_mask]
        gt = gt[valid_mask]

    return H_res, gt

def compute_auc_matrix(H_res, gt, class_id):
    """
    H_res: (L, N, N)
    gt:    (L,)
    """
    L, N, _ = H_res.shape
    auc_mat = np.zeros((N, N))

    y_true = (gt == class_id).astype(np.int32)

    # Skip if class is absent
    if y_true.sum() == 0 or y_true.sum() == len(y_true):
        return np.full((N, N), np.nan)

    for i in range(N):
        for j in range(N):
            scores = H_res[:, i, j]
            auc_mat[i, j] = roc_auc_score(y_true, scores)

    return auc_mat

def auc_analysis_all_classes(H_res, gt, ignore_label=None):
    classes = np.unique(gt)
    if ignore_label is not None:
        classes = classes[classes != ignore_label]

    results = {}
    for c in classes:
        results[c] = compute_auc_matrix(H_res, gt, c)

    return results

def plot_auc_heatmap(auc_mat, class_id, stream_names=None):
    N = auc_mat.shape[0]
    if stream_names is None:
        stream_names = [f"S{i}" for i in range(N)]

    fig = plt.figure(figsize=(4, 4))
    im = plt.imshow(auc_mat, cmap="viridis", vmin=0.5, vmax=1.0)
    plt.colorbar(im, fraction=0.046, pad=0.04)

    plt.xticks(range(N), stream_names, rotation=45)
    plt.yticks(range(N), stream_names)
    plt.xlabel("Target stream (j)")
    plt.ylabel("Source stream (i)")
    plt.title(f"AUC of $\\mathcal{{H}}^{{Res}}(i,j)$ — Class {class_id}")

    plt.tight_layout()
    plt.savefig(f"Analysis_{class_id}.png", bbox_inches="tight")
    plt.close(fig)


def compute_class_means(H_res, gt, num_classes, ignore_label=None):
    """
    H_res: (L, N, N)
    gt:    (L,)
    returns: class_means of shape (N, N, num_classes)
    """
    L, N, _ = H_res.shape
    class_means = np.zeros((N, N, num_classes))

    for c in range(num_classes):
        if ignore_label is not None:
            mask = (gt == c)
        else:
            mask = (gt == c)

        if mask.sum() == 0:
            class_means[:, :, c] = np.nan
            continue    
        class_means[:, :, c] = H_res[mask].mean(axis=0)

    return class_means

def plot_all_interaction_bars(
    class_means,
    stream_names=None,
    class_names=None,
    normalize=True,
    save_dir=None
):
    N = class_means.shape[0]

    for i in range(N):
        for j in range(N):
            scores = class_means[i, j].copy()

            if normalize:
                scores = scores - np.nanmean(scores)

            fig = plt.figure(figsize=(6, 3))
            plt.bar(range(len(scores)), scores)
            plt.xlabel("Class")
            plt.ylabel("Mean interaction score")

            src = stream_names[i] if stream_names else f"S{i}"
            tgt = stream_names[j] if stream_names else f"S{j}"
            plt.title(f"{src} → {tgt}")

            if class_names:
                plt.xticks(range(len(scores)), class_names, rotation=45)
            else:
                plt.xticks(range(len(scores)))

            plt.tight_layout()

            if save_dir:
                plt.savefig(f"{save_dir}/Hres_{i}_{j}.png", dpi=200, bbox_inches="tight")
                plt.close(fig)
            else:
                plt.show()


# ------------------------------------------------------------------------------------
# 9. 测试用例
# ------------------------------------------------------------------------------------
if __name__ == '__main__':
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print(f"使用设备: {device}")
    
    # --- 图像模型测试 ---
    img_model = ImageHyperConnectionTransformer(
        image_size=224, patch_size=16, in_channels=3, num_classes=10,
        dim=512, n_layers=6, n_heads=8, rate=4, dropout=0.1
    )
    img_model = img_model.to(device)
    
    print("\n" + "=" * 60)
    print("Image Hyper-Connections Transformer 模型测试")
    print("=" * 60)
    
    # 运行模型
    dummy_img = torch.randn(4, 3, 224, 224, device=device)
    print(f"输入图像形状: {dummy_img.shape}")
    logits = img_model(dummy_img)
    assert logits.shape == (4, 10), "图像模型输出形状错误！"
    print(f"输出 Logits 形状: {logits.shape} (测试通过)")
    loss = logits.sum(); loss.backward()
    print("图像模型前向及反向传播测试通过。")
    print("-" * 60)

    # --- 文本模型测试 ---
    text_model = HyperConnectionTransformer(
        vocab_size=10000, max_len=512, dim=512, n_layers=6,
        n_heads=8, rate=4, dropout=0.1
    )
    text_model = text_model.to(device)
    
    print("\nHyper-Connections Transformer (文本) 模型测试")
    print("=" * 60)
    
    # 运行模型
    dummy_text = torch.randint(0, 10000, (4, 128), device=device)
    print(f"输入文本形状: {dummy_text.shape}")
    logits = text_model(dummy_text)
    assert logits.shape == (4, 128, 10000), "文本模型输出形状错误！"
    print(f"输出 Logits 形状: {logits.shape} (测试通过)")
    loss = logits.sum(); loss.backward()
    print("文本模型前向及反向传播测试通过。")
    
    print("\n" + "=" * 60)
    print("内存使用测试")
    print("=" * 60)
    
    # 测试模型内存占用
    def get_model_size(model):
        param_size = 0
        buffer_size = 0
        for param in model.parameters():
            param_size += param.nelement() * param.element_size()
        for buffer in model.buffers():
            buffer_size += buffer.nelement() * buffer.element_size()
        return param_size / 1024 / 1024, buffer_size / 1024 / 1024  # 转换为 MB
    
    param_size, buffer_size = get_model_size(img_model)
    print(f"图像模型参数大小: {param_size:.2f} MB")
    print(f"图像模型 Buffer 大小: {buffer_size:.2f} MB")
    
    param_size, buffer_size = get_model_size(text_model)
    print(f"文本模型参数大小: {param_size:.2f} MB")
    print(f"文本模型 Buffer 大小: {buffer_size:.2f} MB")
    print("=" * 60)

    # --- 解码器模型测试 ---
    dec_model = HyperConnectionDecodeTransformer(
        vocab_size=10000, max_len=512, dim=512, n_layers=6,
        n_heads=8, rate=4, dropout=0.1
    )
    dec_model = dec_model.to(device)
    
    print("\nHyper-Connections Decode Transformer (解码器) 模型测试")
    print("=" * 60)
    
    # 运行模型
    dummy_input = torch.randint(0, 10000, (4, 128), device=device)
    print(f"输入序列形状: {dummy_input.shape}")
    logits = dec_model(dummy_input)
    assert logits.shape == (4, 128, 10000), "解码器模型输出形状错误！"
    print(f"输出 Logits 形状: {logits.shape} (测试通过)")
    loss = logits.sum(); loss.backward()
    print("解码器模型前向及反向传播测试通过。")
    print("=" * 60)

